version: "3.9"

services:
  mysql:
    image: mysql:8

    container_name: callmedex-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: no_32f82u14n
      MYSQL_DATABASE: callmedex

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: