ALTER TABLE users 
ADD COLUMN IF NOT EXISTS gender VARCHAR(20) NULL,
ADD COLUMN IF NOT EXISTS dob DATE NULL,
ADD COLUMN IF NOT EXISTS address VARCHAR(255) NULL,
ADD COLUMN IF NOT EXISTS city VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS district VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS state VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS pincode VARCHAR(20) NULL,
ADD COLUMN IF NOT EXISTS country VARCHAR(100) NULL;

ALTER TABLE users MODIFY COLUMN role ENUM(
    'patient',
    'phlebo',
    'doctor',
    'admin',
    'diagnostic',
    'consultancy',
    'pharmacy',
    'organization'
) NOT NULL;