CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NULL,
    patient_name VARCHAR(150) NOT NULL,
    patient_age INT NOT NULL,
    patient_sex VARCHAR(20) NOT NULL,
    patient_mobile VARCHAR(20) NOT NULL,
    patient_email VARCHAR(100) NOT NULL,
    patient_address TEXT NOT NULL,
    branch VARCHAR(100) NOT NULL,
    scans JSON NOT NULL,
    appointment_date DATE NOT NULL,
    time_slot VARCHAR(50) NOT NULL,
    prescription_path VARCHAR(255) NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    status ENUM('pending', 'confirmed', 'completed', 'cancelled') DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
