CREATE TABLE IF NOT EXISTS home_service_categories (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    category_name VARCHAR(150) NOT NULL UNIQUE,
    category_code VARCHAR(100) NOT NULL UNIQUE,
    icon VARCHAR(20) NULL,

    is_active BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);